# Generated by Django 5.1.1 on 2025-03-25 07:55

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0002_alter_admin_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=YellowDealsAPP.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='store_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=YellowDealsAPP.models.store_image_upload_to),
        ),
    ]
