# Generated by Django 5.1.1 on 2025-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0005_remove_product_image_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
