# Generated by Django 5.1.1 on 2025-04-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0006_storeowner_latitude_storeowner_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_pass',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='customer_pass',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='store_pass',
            field=models.CharField(max_length=128),
        ),
    ]
