# Generated by Django 5.1.1 on 2025-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0007_alter_admin_admin_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('active', 'กำลังใช้งาน'), ('banned', 'ถูกแบน')], default='pending', max_length=20),
        ),
    ]
