# Generated by Django 5.1.1 on 2025-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0011_admin_last_login_storeowner_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='register_date',
            field=models.DateField(auto_now_add=True, default='2025-04-21'),
            preserve_default=False,
        ),
    ]
