# Generated by Django 5.1.1 on 2025-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0016_product_is_hidden_product_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
