# Generated by Django 5.1.1 on 2025-04-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0019_alter_product_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_url',
            new_name='product_image',
        ),
    ]
