# Generated by Django 5.1.1 on 2025-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0020_rename_product_url_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
