# Generated by Django 5.1.1 on 2025-05-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0023_alter_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreApproval',
        ),
    ]
