# Generated by Django 5.1.1 on 2025-05-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0025_product_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='store_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='YellowDealsAPP.storeowner'),
        ),
    ]
