# Generated by Django 5.1.1 on 2025-05-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0027_complaint_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='store_complainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_complaints', to='YellowDealsAPP.storeowner'),
        ),
    ]
