# Generated by Django 5.1.1 on 2025-03-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_pass', models.CharField(max_length=15)),
                ('admin_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('customer_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('customer_username', models.CharField(max_length=50)),
                ('customer_pass', models.CharField(max_length=15)),
                ('customer_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('store_owner_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('store_username', models.CharField(max_length=50)),
                ('store_pass', models.CharField(max_length=15)),
                ('store_name', models.CharField(max_length=100)),
                ('store_email', models.CharField(max_length=50)),
                ('store_tel', models.CharField(max_length=10)),
                ('store_address', models.CharField(max_length=255)),
                ('store_image_url', models.CharField(max_length=255)),
                ('store_branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('productType_id', models.AutoField(primary_key=True, serialize=False)),
                ('productType_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStore',
            fields=[
                ('typeStore_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('typeStore_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_date', models.DateTimeField()),
                ('product_details', models.CharField(max_length=255)),
                ('view_count', models.IntegerField(default=0)),
                ('product_url', models.CharField(max_length=255)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.categories')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.storeowner')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.generaluser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.product')),
            ],
        ),
        migrations.CreateModel(
            name='StoreApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=50)),
                ('date_approved', models.DateTimeField()),
                ('approval_details', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.admin')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.storeowner')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_text', models.CharField(max_length=255)),
                ('complaint_status', models.CharField(max_length=50)),
                ('complaint_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.generaluser')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.storeowner')),
            ],
        ),
        migrations.AddField(
            model_name='storeowner',
            name='typeStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YellowDealsAPP.typestore'),
        ),
    ]
