# Generated by Django 5.1.1 on 2025-03-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['admin_id']},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['categories_id']},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['complaint_id']},
        ),
        migrations.AlterModelOptions(
            name='generaluser',
            options={'ordering': ['customer_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='savedproduct',
            options={'ordering': ['saved_id']},
        ),
        migrations.AlterModelOptions(
            name='storeapproval',
            options={'ordering': ['approval_id']},
        ),
        migrations.AlterModelOptions(
            name='storeowner',
            options={'ordering': ['store_owner_id']},
        ),
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'ordering': ['productType_id']},
        ),
        migrations.AlterModelOptions(
            name='typestore',
            options={'ordering': ['typeStore_id']},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='Complaint',
        ),
        migrations.AlterModelTable(
            name='generaluser',
            table='GeneralUser',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='savedproduct',
            table='SavedProduct',
        ),
        migrations.AlterModelTable(
            name='storeapproval',
            table='StoreApproval',
        ),
        migrations.AlterModelTable(
            name='storeowner',
            table='StoreOwner',
        ),
        migrations.AlterModelTable(
            name='typeproduct',
            table='TypeProduct',
        ),
        migrations.AlterModelTable(
            name='typestore',
            table='TypeStore',
        ),
    ]
