# Generated by Django 5.1.1 on 2025-03-25 08:18

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0003_rename_producttype_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='store_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='store_image_url',
            field=models.ImageField(blank=True, default='static/images/Default.png', null=True, upload_to=YellowDealsAPP.models.store_image_upload_to),
        ),
    ]
