# Generated by Django 5.1.1 on 2025-03-25 08:21

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0004_alter_product_product_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.ImageField(blank=True, null=True, upload_to=YellowDealsAPP.models.product_image_upload_to),
        ),
    ]
