# Generated by Django 5.1.1 on 2025-04-21 06:49

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0009_admin_admin_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='store_image_url',
            field=models.ImageField(blank=True, default='../static/images/Default.png', null=True, upload_to=YellowDealsAPP.models.store_image_upload_to),
        ),
    ]
