# Generated by Django 5.1.1 on 2025-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0012_storeowner_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeComplaint',
            fields=[
                ('typeComplaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('typeComplaint_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TypeComplaint',
                'ordering': ['typeComplaint_id'],
            },
        ),
    ]
