# Generated by Django 5.1.1 on 2025-04-27 09:38

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0015_complaint_type_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='store_image_url',
            field=models.ImageField(blank=True, default='../static/images/Default1.png', null=True, upload_to=YellowDealsAPP.models.store_image_upload_to),
        ),
    ]
