# Generated by Django 5.1.1 on 2025-04-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0017_product_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
