# Generated by Django 5.1.1 on 2025-05-18 10:52

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0021_savedproduct_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='images/product.png', null=True, upload_to=YellowDealsAPP.models.product_image_upload_to),
        ),
    ]
