# Generated by Django 5.1.1 on 2025-05-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0024_delete_storeapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
