# Generated by Django 5.1.1 on 2025-05-21 12:31

import YellowDealsAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YellowDealsAPP', '0026_alter_complaint_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_image',
            field=models.ImageField(blank=True, null=True, upload_to=YellowDealsAPP.models.complaint_image_upload_to),
        ),
    ]
